index.html

Changed paragraph content and name for Jacob's biography.

Updates to Contact Section. 

---

index.html

Added bios for Kelsey, Maxx, Jimmy, Isabella, Adam, and Alex. Also added Katie's name and title.

Added six more bios

---

index.html
newsletters/PR.html

- Added Nuclear Science Week video to the outreach section slideshow.
- Changed "Public Relations" section to "Professional Opportunities" and added details about scholarships, internships, and research opportunities.

NSW video & new "Professional Opportunities" section

---

index.html

Replaced Katie's bio with Dario's as the new internal vice president. Also updated Jimmy's bio to reflect NPRE transfer. Standardized the capitalization of "freshman", "sophomore", "junior" and "senior".

Dario's bio, and other bio updates

---

newsletters/PR.html

Added a link to our chapter's Student Conference Interest Form to the Professional section.

Student Conference Interest Form

---

index.html
newsletters/newsletter1.html

Improved the formatting of the list of newsletters. Changed the Market link to open in a new tab. Fixed the alumni link to direct to alumni.html and not letters.html.

Newsletter list formatting, market link, alumni link

---

index.html

Changed Stephen_MotM.jpg to StephenA_MotM.jpg.

Fixed Stephen's headshot's file location

---

css/main.css
index.html

Added slack logo to the header, which links to the ANS Slack channel.
Trying a new layout for the Professional section, with Professional Opportunities box next to the MotM list box.

Slack Icon, and Professional Formatting

---

index.html
letters.html

Made further changes to the formatting of the Professional Opportunities box.

Professional Formatting Changes

---

index.html

Shortened Gavin's write-up to fit the sizing of the MotM slideshow.

Shortened March MotM writeup

---

index.html

Now that the Professional Opportunities box is aligned with the MotM box, the aspect ratio needed to be adjusted to make the PO box narrower. Changed width from 700px to 500px.

Changed aspect ratio of Professional Opportunities

---

newsletters/PR.html

got rid of "Student Conference Interest Form" from professional opportunities box because student conference is over

Removed Student Conference Form from PO

---

index.html

Updated exec board bios to 2019-2020 members

Changing Exec Bios

---

index.html
letters.html

add a Grainger Grove picture and change the meeting slides link

outreach picture & google slides

---

newsletters/PR.html

I think I changed the words in the PR section to white?

Experimental color changes

---

index.html

fixed market link with @acballa2  forever.

Market link

---

index.html

Anna year changed to senior (this is an example for josh)

Exec section update

---

css/main.css
index.html

This PR adds four dropdown menus to the outreach section with link items and closes #67

Outreach links

---

letters.html

This is why we don't merge our own PR's, my bad. It's fixed now.

Button fix on the newsletters page

---

index.html

also makes space for more tabs if Jake wants to add them.

move logos outside row so spacing isn't weird

---

index.html

Updating Poistions

---

index.html

This PR adds our TikTok to the getting connected section of the outreach links.

add tiktok to getting connected section of outreach links
